publish_to: none
version: 0.1.1

name: amos_environment_runner
description: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  window_manager: ^0.4.0
  package_info_plus: ^8.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.json

  fonts:
  - family: Cascadia Code
    fonts:
      - asset: assets/CascadiaCode-ExtraLight.ttf
        weight: 200